### Obtener web por id
GET http://localhost:3000/web/670ea2858e797634d74e04ea

### Crear web
POST http://localhost:3000/web
Content-Type: application/json

{
    "city": "Madrid",
    "activity": "Running",
    "title": "Running in Madrid",
    "summary": "Running in Madrid is a great experience",
    "texts": [ "Madrid is a great city", "Running is a great activity" ],
    "images": [ "madrid.jpg", "running.jpg" ],
    "reviews": 
        { 
            "scoring":5,
            "points":5,
            "review":"Great experience" 
        }
    
}

### Actualizar web
PUT http://localhost:3000/web/670ea2858e797634d74e04ea
Content-Type: application/json

{
    "city": "Madrid",
    "activity": "Running",
    "title": "Running in Madrid",
    "summary": "Running in Madrid is a great experience",
    "texts": [ "Madrid is a great city", "Running is a great activity" ],
    "images": [ "madrid.jpg", "running.jpg" ],
    "reviews": 
        { 
            "scoring":4,
            "points":4,
            "review":"Great experience" 
        }
    
}

### Archivar web
DELETE http://localhost:3000/web/670ea2858e797634d74e04ea?typeDelete=logical

### Borrar web
DELETE http://localhost:3000/web/670ea2858e797634d74e04ea?typeDelete=physical

### Subir imagen a array de imagenes de la web
PATCH http://localhost:3000/web/670ea2858e797634d74e04ea HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="img.jpg"
Content-Type: image/jpeg

# para que sepa cual es el archivo
< ./img.jpg 
--Boundry--


