### Obtener la lista de comercios
GET http://localhost:3000/comercio 

### Obtener la lista de comercios ordenada
GET http://localhost:3000/comercio?order=asc


### Obtener un comercio por su cif
GET http://localhost:3000/comercio/12345681A

### Crear un comercio, para crear más de uno, hay que ir cambiando el cif ya que es unico
POST http://localhost:3000/comercio
Content-Type: application/json

{
    "name": "comercio 1",
    "cif": "12345684A",
    "email": "comercio1@gmail.com",
    "phone": "123456789",
    "page_id": "23804"
}

### Actualizar un comercio a partir de su CIF
PUT http://localhost:3000/comercio/12345681A
Content-Type: application/json

{
    "name": "Hola que tal estas",
    "cif": "12345681A",
    "email": "comercio1@gmail.com",
    "phone": "123456789",
    "page_id": "23923" 
}

### Borrar un comercio a partir de su CIF borrado logico
DELETE http://localhost:3000/comercio/12345670A?hard=false

### Borrar un comercio a partir de su CIF borrado fisico
DELETE http://localhost:3000/comercio/12345683A?hard=true
