### Obtener la lista de comercios
GET http://localhost:3000/comercio 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFiN2M4ODM2YjQ2ZjJjNDhiNDE0NTQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzI5ODU1MzkzLCJleHAiOjE3Mjk5NDE3OTN9.UN8UoL8j1uTJnYWIAA5uXsS_YAy9WHCJEU70YZ00t6Q

### Obtener la lista de comercios ordenada
GET http://localhost:3000/comercio?order=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFiN2M4ODM2YjQ2ZjJjNDhiNDE0NTQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzI5ODU1MzkzLCJleHAiOjE3Mjk5NDE3OTN9.UN8UoL8j1uTJnYWIAA5uXsS_YAy9WHCJEU70YZ00t6Q

### Obtener un comercio por su cif
GET http://localhost:3000/comercio/12345684A
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFiN2M4ODM2YjQ2ZjJjNDhiNDE0NTQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzI5ODU1MzkzLCJleHAiOjE3Mjk5NDE3OTN9.UN8UoL8j1uTJnYWIAA5uXsS_YAy9WHCJEU70YZ00t6Q

### Crear un comercio
POST http://localhost:3000/comercio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFiN2M4ODM2YjQ2ZjJjNDhiNDE0NTQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzI5ODU1MzkzLCJleHAiOjE3Mjk5NDE3OTN9.UN8UoL8j1uTJnYWIAA5uXsS_YAy9WHCJEU70YZ00t6Q
Content-Type: application/json

{
    "name": "comercio 1",
    "cif": "12345685A",
    "email": "comercio2@gmail.com",
    "phone": "123456789",
    "page_id": "23805"
}

### Actualizar un comercio a partir de su CIF
PUT http://localhost:3000/comercio/12345684A
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFiN2M4ODM2YjQ2ZjJjNDhiNDE0NTQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzI5ODU1MzkzLCJleHAiOjE3Mjk5NDE3OTN9.UN8UoL8j1uTJnYWIAA5uXsS_YAy9WHCJEU70YZ00t6Q
Content-Type: application/json

{
    "name": "Hola que tal estas",
    "cif": "12345681A",
    "email": "comercio1@gmail.com",
    "phone": "123456789",
    "page_id": "23923" 
}

### Borrar un comercio a partir de su CIF borrado logico
DELETE http://localhost:3000/comercio/12345684A?hard=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFiN2M4ODM2YjQ2ZjJjNDhiNDE0NTQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzI5ODU1MzkzLCJleHAiOjE3Mjk5NDE3OTN9.UN8UoL8j1uTJnYWIAA5uXsS_YAy9WHCJEU70YZ00t6Q

### Borrar un comercio a partir de su CIF borrado fisico
DELETE http://localhost:3000/comercio/12345684A?hard=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzFiN2M4ODM2YjQ2ZjJjNDhiNDE0NTQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzI5ODU1MzkzLCJleHAiOjE3Mjk5NDE3OTN9.UN8UoL8j1uTJnYWIAA5uXsS_YAy9WHCJEU70YZ00t6Q
